[tool.poetry]
name = "nukeserversocket"
version = "0.1.0"
description = ""
authors = ["virgilsisoe <sisoe24@gmail.com>"]

[tool.poetry.dependencies]
python = ">=2.7.16, ^3.7"
PySide2 = "5.12.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-qt = "^4.0.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
