name: NukeServerSocket
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  pull_request_target:
    branches:
      - main
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, windows-latest]
        python-version: ["3.7", "3.9", "3.10"]
      fail-fast: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: |
        pip install --upgrade pip
        pip install PySide2==5.15.2.1
        pip install pytest==7.4.3
        pip install tox==4.8.0
        pip install pytest-qt==4.2.0
        pip install pytest-cov==4.1.0
        pip install pytest-repeat==0.9.3
        pip install pytest-randomly==3.12.0
        pip install -e .

      
    - name: Debug Information
      run: |
        echo "Python version: $(python --version)"
        echo "Pip version: $(pip --version)"
        echo "Installed packages:"
        pip list
        echo "Python path:"
        python -c "import sys; print(sys.path)"
        echo "Can we import nukeserversocket.settings?"
        python -c "import nukeserversocket.settings; print('Success!')"
  
    - name: Run tests
      run: |
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -R
        echo "Which pytest"
        which pytest
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest -v
    
    - name: Debug on failure
      if: failure()
      run: |
        echo "Test failure occurred. Debugging information:"
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -R
        echo "Python path:"
        python -c "import sys; print(sys.path)"
        echo "Content of site-packages:"
        ls $(python -c "import site; print(site.getsitepackages()[0])")
        echo "Trying to import nukeserversocket.settings:"
        python -c "import nukeserversocket.settings; print('Settings import successful')"
